site_name: Gen3 User Doc
site_url: https://uc-cdis.github.io/gen3-user-doc/
site_description: Gen3 Data Commons Docuementation
site_author: University of Chicago, CDIS

repo_url: https://github.com/uc-cdis/gen3-user-doc/
edit_uri: ""

pages:
    - Home: index.md
    - About Gen3: about/about.md
    - Data Contribution:
        - Contribution Overview: data-contribution/contribution-overview.md
        - 1. Legal Agreement: data-contribution/1-legal.md
        - 2. Submit Data Inventory Form: data-contribution/2-data-inventory.md
        - 3. Get API credentials: data-contribution/3-api-creds.md
        - 4. Prepare metadata: data-contribution/4-prep-meta.md
        - 5. Access metadata: data-contribution/5-access-meta.md
        - 6. Submit metadata: data-contribution/6-submit-meta.md
        - 7. Get s3 credentials: data-contribution/7-s3-cred.md
        - 8. Upload Data: data-contribution/8-upload.md
    - Data Access:
        - Access Overview: data-access/access-overview.md
        - 1. Send Credentials: data-access/1-send-cred.md
        - 2. Configure SSH: data-access/2-ssh.md
        - 3. Get access: data-access/3-access-data.md
    - Appendices:
        - Data Dictionary: appendices/data-dictionary.md
        - Minimal Technical Data Elements: appendices/mtde.md
        - Working with the Proxy and Whitelist: appendices/proxy-whitelist.md
        - Working with the API: appendices/api.md
    - DEMOs:
        - BloodPAC: demos/bloodpac-demo.md


extra_css:
    - css/extra.css

markdown_extensions:
    - toc:
        permalink: 
    - admonition
    - def_list

copyright: Copyright &copy; 2017 <a href="https://cdis.uchicago.edu">CDIS at UChicago</a>
google_analytics: ['UA-27795084-5', 'mkdocs.org']

plugins:
    - search
